/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BlizzardOracleRouter } from "./BlizzardOracleRouter";
export type { CustomerContract } from "./CustomerContract";
